nav:
  - README.md
  - About: about.md
  - md/index/index.md
  - Test:
    - md/Test/
  - Library:
    - md/*
  - HTML: html/index.html
  - PDF: pdf/index.pdf

preserve_directory_names: true

sort:
  sections: mixed