nav:
  - index.md
  - Test:
    - md/index/index.md
    - md/Test/*
  - Library:
    - md/Library/index.md
    - md/*
  - HTML: html/index.html
  # - PDF: pdf/index.pdf

preserve_directory_names: true

sort:
  sections: mixed