nav:
  - index.md
  - Test:
    - md/Test/All/index.md
    - Test3: md/Test/index.md
    - md/Test/
  - Library:
    - Library/index.md
    - md/*
  - HTML: html/Test.All.html
  - PDF: pdf/Test.All.pdf

preserve_directory_names: true

sort:
  sections: mixed