nav:
  - index.md
  - Test:
    - md/index/index.md
    - Test3: md/Test/index.md
    - md/Test/
  - Library:
    - Library/index.md
    - md/*
  - HTML: html/index.html
  - PDF: pdf/index.pdf

preserve_directory_names: true

sort:
  sections: mixed