nav:
  - about.md
  - README: 
    - README.md
    - user-guide.md
  - Test:
    - Test/index.md
    - Test2: md/Test2/index.md
    - Test3: md/Test3/index.md
    - md/Test/
  - Library:
    - Library/index.md
    - md/*
  - HTML: html/Test.All.html
  - PDF: pdf/Test.All.pdf

preserve_directory_names: true

sort:
  sections: mixed