nav:
  - about.md
  - README: 
    - README.md
    - user-guide.md
  - Test:
    - Test/index.md
    - Test: md/Test/index.md
    - Test2: md/Test2/index.md
    - md/Test/
  - Library:
    - Library/index.md
    - md/*
  - HTML: html/Test.index.html
  - PDF: pdf/Test.index.pdf

preserve_directory_names: true

sort:
  sections: mixed