nav:
  - about.md
  - README: 
    - README.md
    - user-guide.md
  - Test:
    - Test/index.md
    - Test: md/Test/index.md
    - Test2: md/Test2/index.md
    - TestMd: md/TestMd/index.md
    - md/Test/
  - Library:
    - Library/index.md
    - md/*
  - HTML: html/Test.index.html

preserve_directory_names: true

sort:
  sections: mixed