nav:
  - README: 
    - README.md
    - about.md
    - user-guide.md
    - CHANGELOG: https://github.com/pdmosses/agda-material/blob/main/CHANGELOG.md
  - Test:
    - Test/index.md
    - md/Test/
  - Library:
    - Library/index.md
    - md/*
  - HTML: html/Test.index.html

preserve_directory_names: true

sort:
  sections: mixed